onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /axi_tb/clock
add wave -noupdate /axi_tb/reset_n
add wave -noupdate /axi_tb/AWADDR
add wave -noupdate /axi_tb/AWLEN
add wave -noupdate /axi_tb/WDATA
add wave -noupdate /axi_tb/AWSIZE
add wave -noupdate /axi_tb/AWBURST
add wave -noupdate /axi_tb/AWCACHE
add wave -noupdate /axi_tb/AWVALID
add wave -noupdate /axi_tb/ARADDR
add wave -noupdate /axi_tb/ARLEN
add wave -noupdate /axi_tb/ARSIZE
add wave -noupdate /axi_tb/ARBURST
add wave -noupdate /axi_tb/ARCACHE
add wave -noupdate /axi_tb/ARVALID
add wave -noupdate /axi_tb/aw_addr
add wave -noupdate /axi_tb/ar_addr
add wave -noupdate /axi_tb/aw_len
add wave -noupdate /axi_tb/ar_len
add wave -noupdate /axi_tb/aw_size
add wave -noupdate /axi_tb/ar_size
add wave -noupdate /axi_tb/w_data
add wave -noupdate /axi_tb/r_data
add wave -noupdate /axi_tb/aw_burst
add wave -noupdate /axi_tb/ar_burst
add wave -noupdate /axi_tb/aw_cache
add wave -noupdate /axi_tb/ar_cache
add wave -noupdate /axi_tb/aw_valid
add wave -noupdate /axi_tb/ar_valid
add wave -noupdate /axi_tb/aw_ready
add wave -noupdate /axi_tb/ar_ready
add wave -noupdate /axi_tb/w_ready
add wave -noupdate /axi_tb/w_valid
add wave -noupdate /axi_tb/w_last
add wave -noupdate /axi_tb/w_strb
add wave -noupdate /axi_tb/r_ready
add wave -noupdate /axi_tb/r_valid
add wave -noupdate /axi_tb/r_last
add wave -noupdate /axi_tb/b_ready
add wave -noupdate /axi_tb/b_valid
add wave -noupdate /axi_tb/b_resp
add wave -noupdate /axi_tb/r_resp
add wave -noupdate /axi_tb/read_data
add wave -noupdate /axi_tb/total_test
add wave -noupdate /axi_tb/pass_test
add wave -noupdate /axi_tb/fail_test
add wave -noupdate /axi_tb/i
add wave -noupdate /axi_tb/rand_addr
add wave -noupdate /axi_tb/rand_data
add wave -noupdate /axi_tb/axi_m/aclk
add wave -noupdate /axi_tb/axi_m/areset_n
add wave -noupdate /axi_tb/axi_m/aw_ready
add wave -noupdate /axi_tb/axi_m/aw_addr
add wave -noupdate /axi_tb/axi_m/aw_len
add wave -noupdate /axi_tb/axi_m/aw_size
add wave -noupdate /axi_tb/axi_m/aw_burst
add wave -noupdate /axi_tb/axi_m/aw_cache
add wave -noupdate /axi_tb/axi_m/aw_valid
add wave -noupdate /axi_tb/axi_m/w_ready
add wave -noupdate /axi_tb/axi_m/w_data
add wave -noupdate /axi_tb/axi_m/w_valid
add wave -noupdate /axi_tb/axi_m/w_last
add wave -noupdate /axi_tb/axi_m/w_strb
add wave -noupdate /axi_tb/axi_m/b_valid
add wave -noupdate /axi_tb/axi_m/b_ready
add wave -noupdate /axi_tb/axi_m/b_resp
add wave -noupdate /axi_tb/axi_m/ar_ready
add wave -noupdate /axi_tb/axi_m/ar_addr
add wave -noupdate /axi_tb/axi_m/ar_len
add wave -noupdate /axi_tb/axi_m/ar_size
add wave -noupdate /axi_tb/axi_m/ar_burst
add wave -noupdate /axi_tb/axi_m/ar_cache
add wave -noupdate /axi_tb/axi_m/ar_valid
add wave -noupdate /axi_tb/axi_m/r_ready
add wave -noupdate /axi_tb/axi_m/r_data
add wave -noupdate /axi_tb/axi_m/r_valid
add wave -noupdate /axi_tb/axi_m/r_last
add wave -noupdate /axi_tb/axi_m/r_resp
add wave -noupdate /axi_tb/axi_m/AWADDR
add wave -noupdate /axi_tb/axi_m/AWLEN
add wave -noupdate /axi_tb/axi_m/WDATA
add wave -noupdate /axi_tb/axi_m/AWSIZE
add wave -noupdate /axi_tb/axi_m/AWBURST
add wave -noupdate /axi_tb/axi_m/AWCACHE
add wave -noupdate /axi_tb/axi_m/AWVALID
add wave -noupdate /axi_tb/axi_m/ARADDR
add wave -noupdate /axi_tb/axi_m/ARLEN
add wave -noupdate /axi_tb/axi_m/ARSIZE
add wave -noupdate /axi_tb/axi_m/ARBURST
add wave -noupdate /axi_tb/axi_m/ARCACHE
add wave -noupdate /axi_tb/axi_m/ARVALID
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aclk
add wave -noupdate /axi_tb/axi_m/master_wr_inst/areset_n
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_ready
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_addr
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_len
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_size
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_burst
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_cache
add wave -noupdate /axi_tb/axi_m/master_wr_inst/aw_valid
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_ready
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_data
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_valid
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_last
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_strb
add wave -noupdate /axi_tb/axi_m/master_wr_inst/b_valid
add wave -noupdate /axi_tb/axi_m/master_wr_inst/b_ready
add wave -noupdate /axi_tb/axi_m/master_wr_inst/b_resp
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWADDR
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWLEN
add wave -noupdate /axi_tb/axi_m/master_wr_inst/WDATA
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWSIZE
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWBURST
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWCACHE
add wave -noupdate /axi_tb/axi_m/master_wr_inst/AWVALID
add wave -noupdate /axi_tb/axi_m/master_wr_inst/w_data_sent
add wave -noupdate /axi_tb/axi_m/master_wr_inst/state
add wave -noupdate /axi_tb/axi_m/master_rd_inst/aclk
add wave -noupdate /axi_tb/axi_m/master_rd_inst/areset_n
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_ready
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_addr
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_len
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_size
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_burst
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_cache
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ar_valid
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_ready
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_data
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_valid
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_last
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_resp
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARADDR
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARLEN
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARSIZE
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARBURST
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARCACHE
add wave -noupdate /axi_tb/axi_m/master_rd_inst/ARVALID
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_data_int
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_valid_int
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_last_int
add wave -noupdate /axi_tb/axi_m/master_rd_inst/r_resp_int
add wave -noupdate /axi_tb/axi_m/master_rd_inst/state
add wave -noupdate /axi_tb/axi_s/aclk
add wave -noupdate /axi_tb/axi_s/areset_n
add wave -noupdate /axi_tb/axi_s/aw_ready
add wave -noupdate /axi_tb/axi_s/aw_addr
add wave -noupdate /axi_tb/axi_s/aw_len
add wave -noupdate /axi_tb/axi_s/aw_size
add wave -noupdate /axi_tb/axi_s/aw_burst
add wave -noupdate /axi_tb/axi_s/aw_cache
add wave -noupdate /axi_tb/axi_s/aw_valid
add wave -noupdate /axi_tb/axi_s/w_ready
add wave -noupdate /axi_tb/axi_s/w_data
add wave -noupdate /axi_tb/axi_s/w_valid
add wave -noupdate /axi_tb/axi_s/w_last
add wave -noupdate /axi_tb/axi_s/w_strb
add wave -noupdate /axi_tb/axi_s/b_valid
add wave -noupdate /axi_tb/axi_s/b_ready
add wave -noupdate /axi_tb/axi_s/b_resp
add wave -noupdate /axi_tb/axi_s/ar_ready
add wave -noupdate /axi_tb/axi_s/ar_addr
add wave -noupdate /axi_tb/axi_s/ar_len
add wave -noupdate /axi_tb/axi_s/ar_size
add wave -noupdate /axi_tb/axi_s/ar_burst
add wave -noupdate /axi_tb/axi_s/ar_cache
add wave -noupdate /axi_tb/axi_s/ar_valid
add wave -noupdate /axi_tb/axi_s/r_ready
add wave -noupdate /axi_tb/axi_s/r_data
add wave -noupdate /axi_tb/axi_s/r_valid
add wave -noupdate /axi_tb/axi_s/r_last
add wave -noupdate /axi_tb/axi_s/r_resp
add wave -noupdate /axi_tb/axi_s/mem_aw_addr
add wave -noupdate /axi_tb/axi_s/mem_aw_len
add wave -noupdate /axi_tb/axi_s/wr_len
add wave -noupdate /axi_tb/axi_s/mem_aw_size
add wave -noupdate /axi_tb/axi_s/mem_aw_burst
add wave -noupdate /axi_tb/axi_s/mem_aw_cache
add wave -noupdate /axi_tb/axi_s/mem_aw_valid
add wave -noupdate /axi_tb/axi_s/mem_w_data
add wave -noupdate /axi_tb/axi_s/mem_w_valid
add wave -noupdate /axi_tb/axi_s/mem_w_last
add wave -noupdate /axi_tb/axi_s/mem_w_strb
add wave -noupdate /axi_tb/axi_s/ready
add wave -noupdate /axi_tb/axi_s/wr_en
add wave -noupdate /axi_tb/axi_s/wr_resp
add wave -noupdate /axi_tb/axi_s/wr_state
add wave -noupdate /axi_tb/axi_s/wr_next_state
add wave -noupdate /axi_tb/axi_s/latch_wr_ctrl
add wave -noupdate /axi_tb/axi_s/latch_wr_data
add wave -noupdate /axi_tb/axi_s/mem_ar_addr
add wave -noupdate /axi_tb/axi_s/mem_ar_len
add wave -noupdate /axi_tb/axi_s/mem_ar_size
add wave -noupdate /axi_tb/axi_s/mem_ar_burst
add wave -noupdate /axi_tb/axi_s/mem_ar_cache
add wave -noupdate /axi_tb/axi_s/rd_len
add wave -noupdate /axi_tb/axi_s/rd_en
add wave -noupdate /axi_tb/axi_s/rd_ar_ready
add wave -noupdate /axi_tb/axi_s/latch_rd_ctrl
add wave -noupdate /axi_tb/axi_s/send_data_flag
add wave -noupdate /axi_tb/axi_s/last_data_flag
add wave -noupdate /axi_tb/axi_s/rd_state
add wave -noupdate /axi_tb/axi_s/rd_next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {9066750 ps}
